const ret = [
  {
    label: 'Etc/GMT-10',
    offset: -10,
    value: 'Pacific/Honolulu',
    offsetString: '-10:00',
  },
  {
    label: 'Etc/GMT-10',
    offset: -10,
    value: 'US/Hawaii',
    offsetString: '-10:00',
  },
  {
    label: 'Etc/GMT-9',
    offset: -9,
    value: 'US/Alaska',
    offsetString: '-9:00',
  },
  {
    label: 'Etc/GMT-9',
    offset: -9,
    value: 'America/Anchorage',
    offsetString: '-9:00',
  },
  {
    label: 'Etc/GMT-9',
    offset: -9,
    value: 'America/Nome',
    offsetString: '-9:00',
  },
  {
    label: 'Etc/GMT-8',
    offset: -8,
    value: 'Canada/Pacific',
    offsetString: '-8:00',
  },
  {
    label: 'Etc/GMT-8',
    offset: -8,
    value: 'America/Los_Angeles',
    offsetString: '-8:00',
  },
  {
    label: 'Etc/GMT-8',
    offset: -8,
    value: 'US/Pacific',
    offsetString: '-8:00',
  },
  {
    label: 'Etc/GMT-7',
    offset: -7,
    value: 'Canada/Yukon',
    offsetString: '-7:00',
  },
  {
    label: 'Etc/GMT-7',
    offset: -7,
    value: 'US/Arizona',
    offsetString: '-7:00',
  },
  {
    label: 'Etc/GMT-7',
    offset: -7,
    value: 'America/Inuvik',
    offsetString: '-7:00',
  },
  {
    label: 'Etc/GMT-7',
    offset: -7,
    value: 'America/Boise',
    offsetString: '-7:00',
  },
  {
    label: 'Etc/GMT-7',
    offset: -7,
    value: 'America/Ojinaga',
    offsetString: '-7:00',
  },
  {
    label: 'Etc/GMT-7',
    offset: -7,
    value: 'Canada/Mountain',
    offsetString: '-7:00',
  },
  {
    label: 'Etc/GMT-6',
    offset: -6,
    value: 'America/Guatemala',
    offsetString: '-6:00',
  },
  {
    label: 'Etc/GMT-6',
    offset: -6,
    value: 'America/Belize',
    offsetString: '-6:00',
  },
  {
    label: 'Etc/GMT-6',
    offset: -6,
    value: 'America/Chicago',
    offsetString: '-6:00',
  },
  {
    label: 'Etc/GMT-6',
    offset: -6,
    value: 'Canada/Central',
    offsetString: '-6:00',
  },
  {
    label: 'Etc/GMT-6',
    offset: -6,
    value: 'Canada/Saskatchewan',
    offsetString: '-6:00',
  },
  {
    label: 'Etc/GMT-5',
    offset: -5,
    value: 'America/Panama',
    offsetString: '-5:00',
  },
  {
    label: 'Etc/GMT-5',
    offset: -5,
    value: 'America/Indiana/Petersburg',
    offsetString: '-5:00',
  },
  {
    label: 'Etc/GMT-5',
    offset: -5,
    value: 'Cuba',
    offsetString: '-5:00',
  },
  {
    label: 'Etc/GMT-5',
    offset: -5,
    value: 'Pacific/Easter',
    offsetString: '-5:00',
  },
  {
    label: 'Etc/GMT-5',
    offset: -5,
    value: 'America/Iqaluit',
    offsetString: '-5:00',
  },
  {
    label: 'Etc/GMT-5',
    offset: -5,
    value: 'US/Eastern',
    offsetString: '-5:00',
  },
  {
    label: 'Etc/GMT-5',
    offset: -5,
    value: 'Canada/Eastern',
    offsetString: '-5:00',
  },
  {
    label: 'Etc/GMT-5',
    offset: -5,
    value: 'America/Toronto',
    offsetString: '-5:00',
  },
  {
    label: 'Etc/GMT-4',
    offset: -4,
    value: 'Canada/Atlantic',
    offsetString: '-4:00',
  },
  {
    label: 'Etc/GMT-4',
    offset: -4,
    value: 'America/Manaus',
    offsetString: '-4:00',
  },
  {
    label: 'Etc/GMT-4',
    offset: -4,
    value: 'Atlantic/Bermuda',
    offsetString: '-4:00',
  },
  {
    label: 'Etc/GMT-4',
    offset: -4,
    value: 'Brazil/West',
    offsetString: '-4:00',
  },
  {
    label: 'Etc/GMT-3:30',
    value: 'Canada/Newfoundland',
    offset: -3.5,
    offsetString: '-3:30',
  },
  {
    label: 'Etc/GMT-3',
    offset: -3,
    value: 'Chile/Continental',
    offsetString: '-3:00',
  },
  {
    label: 'Etc/GMT-3',
    offset: -3,
    value: 'America/Argentina/Cordoba',
    offsetString: '-3:00',
  },
  {
    label: 'Etc/GMT-3',
    offset: -3,
    value: 'Brazil/East',
    offsetString: '-3:00',
  },
  {
    label: 'Etc/GMT-3',
    offset: -3,
    value: 'America/Recife',
    offsetString: '-3:00',
  },
  {
    label: 'Etc/GMT-3',
    offset: -3,
    value: 'America/Santiago',
    offsetString: '-3:00',
  },
  {
    label: 'Etc/GMT-2',
    offset: -2,
    value: 'Atlantic/South_Georgia',
    offsetString: '-2:00',
  },
  {
    label: 'Etc/GMT-1',
    offset: -1,
    value: 'Atlantic/Cape_Verde',
    offsetString: '-1:00',
  },
  {
    label: 'Etc/GMT+0',
    offset: 0,
    value: 'Europe/London',
    offsetString: '+0:00',
  },
  {
    label: 'Etc/GMT+0',
    value: 'Atlantic/St_Helena',
    offset: 0,
    offsetString: '+0:00',
  },
  {
    label: 'Etc/GMT+0',
    offset: 0,
    value: 'Iceland',
    offsetString: '+0:00',
  },
  {
    label: 'Etc/GMT+0',
    offset: 0,
    value: 'Atlantic/Canary',
    offsetString: '+0:00',
  },
  {
    label: 'Etc/GMT+1',
    offset: 1,
    value: 'Europe/Rome',
    offsetString: '+1:00',
  },
  {
    label: 'Etc/GMT+1',
    offset: 1,
    value: 'Europe/Berlin',
    offsetString: '+1:00',
  },
  {
    label: 'Etc/GMT+1',
    offset: 1,
    value: 'Europe/Paris',
    offsetString: '+1:00',
  },
  {
    label: 'Etc/GMT+1',
    offset: 1,
    value: 'Africa/Luanda',
    offsetString: '+1:00',
  },
  {
    label: 'Etc/GMT+1',
    offset: 1,
    value: 'Atlantic/Jan_Mayen',
    offsetString: '+1:00',
  },
  {
    label: 'Etc/GMT+2',
    offset: 2,
    value: 'Africa/Cairo',
    offsetString: '+2:00',
  },
  {
    label: 'Etc/GMT+3',
    offset: 3,
    value: 'Europe/Moscow',
    offsetString: '+3:00',
  },
  {
    label: 'Etc/GMT+4',
    offset: 4,
    value: 'Asia/Dubai',
    offsetString: '+4:00',
  },
  {
    label: 'Etc/GMT+6',
    offset: 6,
    value: 'Asia/Kashgar',
    offsetString: '+6:00',
  },
  {
    label: 'Etc/GMT+7',
    offset: 7,
    value: 'Asia/Vientiane',
    offsetString: '+7:00',
  },
  {
    label: 'Etc/GMT+8',
    offset: 8,
    value: 'Asia/Chungking',
    offsetString: '+8:00',
  },
  {
    label: 'Etc/GMT+8',
    offset: 8,
    value: 'Asia/Macao',
    offsetString: '+8:00',
  },
  {
    label: 'Etc/GMT+8',
    offset: 8,
    value: 'Asia/Shanghai',
    offsetString: '+8:00',
  },
  {
    label: 'Etc/GMT+8',
    offset: 8,
    value: 'Asia/Taipei',
    offsetString: '+8:00',
  },
  {
    label: 'Etc/GMT+8',
    offset: 8,
    value: 'PRC',
    offsetString: '+8:00',
  },
  {
    label: 'Etc/GMT+8',
    offset: 8,
    value: 'Asia/Hong_Kong',
    offsetString: '+8:00',
  },
  {
    label: 'Etc/GMT+9',
    offset: 9,
    value: 'Asia/Jayapura',
    offsetString: '+9:00',
  },
  {
    label: 'Etc/GMT+9',
    offset: 9,
    value: 'Asia/Seoul',
    offsetString: '+9:00',
  },
  {
    label: 'Etc/GMT+9:30',
    value: 'Australia/North',
    offset: 9.5,
    offsetString: '+9:30',
  },
  {
    label: 'Etc/GMT+10',
    offset: 10,
    value: 'Pacific/Yap',
    offsetString: '+10:00',
  },
  {
    label: 'Etc/GMT+10',
    offset: 10,
    value: 'Australia/Lindeman',
    offsetString: '+10:00',
  },
  {
    label: 'Etc/GMT+10:30',
    value: 'Australia/South',
    offset: 10.5,
    offsetString: '+10:30',
  },
  {
    label: 'Etc/GMT+11',
    offset: 11,
    value: 'Australia/Canberra',
    offsetString: '+11:00',
  },
  {
    label: 'Etc/GMT+11',
    offset: 11,
    value: 'Australia/Sydney',
    offsetString: '+11:00',
  },
  {
    label: 'Etc/GMT+11',
    offset: 11,
    value: 'Australia/Melbourne',
    offsetString: '+11:00',
  },
];
